language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - emkristi@stud.ntnu.no
      - kimia.abtahi@gmail.com
      - dina@rosvoll.no
    on_success: never # default: change
    on_failure: always # default: always
